#include <math.h> 
float sqrtf(float x)
{ 
 return sqrt(x);
}

void * AmigaMesaGetConfig()
{
 return 0; 
}

void * AmigaMesaCreateContext()
{
 return 0; 
}

void * AmigaMesaDestroyContext()
{
 return 0; 
}

void * AmigaMesaSetRast()
{
 return 0; 
}

void * AmigaMesaMakeCurrent()
{
 return 0; 
}
void * AmigaMesaSwapBuffers()
{
 return 0; 
}
void glClearIndex(){}
void glClearColor(){}
void glPushAttrib(){}
void glHint(){}
void glClear(){}
void glIndexMask(){}
void glColorMask(){}
void glAlphaFunc(){}
void glBlendFunc(){}
void glLogicOp(){}
void glCullFace(){}
void glFrontFace(){}
void glPointSize(){}
void glLineWidth(){}
void glLineStipple(){}
void glPolygonMode(){}
void glPolygonOffset(){}
void glPolygonStipple(){}
void glEdgeFlag(){}
void glGetPolygonStipple(){}
void glEdgeFlagv(){}
void glScissor(){}
void glClipPlane(){}
void glGetClipPlane(){}
void glDrawBuffer(){}
void glReadBuffer(){}
void glEnable(){}
void glDisable(){} 
void glIsEnabled(){}
void glEnableClientState(){}
void glDisableClientState(){}
void glGetBooleanv(){}
void glGetDoublev(){}
void glGetFloatv(){}
void glGetIntegerv(){}
void glPopAttrib(){}
void glPushClientAttrib(){}
void glPopClientAttrib(){}
void glRenderMode(){}
void glGetError(){}
void glGetString(){}
void glFinish(){}
void glFlush(){}
void glClearDepth(){}
void glDepthFunc(){}
void glDepthMask(){}
void glDepthRange(){}
void glClearAccum(){}
void glAccum(){}
void glMatrixMode(){}
void glOrtho(){}
void glFrustum(){}
void glViewport(){}
void glPushMatrix(){}
void glPopMatrix(){}
void glLoadIdentity(){}
void glLoadMatrixd(){}
void glLoadMatrixf(){}
void glMultMatrixd(){}
void glMultMatrixf(){}
void glRotated(){}
void glRotatef(){}
void glScaled(){}
void glScalef(){}
void glTranslated(){}
void glTranslatef(){}
void gllsList(){}
void glDeleteLists(){}
void glIsList(){}
void glGenLists(){}
void glNewList(){}
void glEndList(){}
void glCallList(){}
void glCallLists(){}
void glListBase(){}
void glBegin(){}
void glEnd(){}
void glVertex2d(){}
void glVertex2f(){}
void glVertex2i(){}
void glVertex2s(){}
void glVertex3d(){}
void glVertex3f(){}
void glVertex3i(){}
void glVertex3s(){}
void glVertex4d(){}
void glVertex4f(){}
void glVertex4i(){}
void glVertex4s(){}
void glVertex2dv(){}
void glVertex2fv(){}
void glVertex2iv(){}
void glVertex2sv(){}
void glVertex3dv(){}
void glVertex3fv(){}
void glVertex3iv(){}
void glVertex3sv(){}
void glVertex4dv(){}
void glVertex4fv(){}
void glVertex4iv(){}
void glVertex4sv(){}

void glNormal3b(){}
void glNormal3d(){}
void glNormal3f(){}
void glNormal3i(){}
void glNormal3s(){}
void glNormal3bv(){}
void glNormal3dv(){}
void glNormal3fv(){}
void glNormal3iv(){}
void glNormal3sv(){}
void glIndexd(){}
void glIndexf(){}
void glIndexi(){}
void glIndexs(){}
void glIndexub(){}
void glIndexdv(){}
void glIndexfv(){}
void glIndexiv(){}
void glIndexsv(){}
void glIndexubv(){}
void glColor3b(){}
void glColor3d(){}
void glColor3f(){}
void glColor3i(){}
void glColor3s(){}
void glColor3ub(){}
void glColor3ui(){}
void glColor3us(){}
void glColor4b(){}
void glColor4d(){}
void glColor4f(){}
void glColor4i(){}
void glColor4s(){}
void glColor4ub(){}
void glColor4ui(){}
void glColor4us(){}
void glColor3bv(){}
void glColor3dv(){}
void glColor3fv(){}
void glColor3iv(){}
void glColor3sv(){}
void glColor3ubv(){}
void glColor3uiv(){}
void glColor3usv(){}
void glColor4bv(){}
void glColor4dv(){}
void glColor4fv(){}
void glColor4iv(){}
void glColor4sv(){}
void glColor4ubv(){}
void glColor4uiv(){}
void glColor4usv(){}
void glTexCoord1d(){}
void glTexCoord1f(){}
void glTexCoord1i(){}
void glTexCoord1s(){}
void glTexCoord2d(){}
void glTexCoord2f(){}
void glTexCoord2i(){}
void glTexCoord2s(){}
void glTexCoord3d(){}
void glTexCoord3f(){}
void glTexCoord3i(){}
void glTexCoord3s(){}
void glTexCoord4d(){}
void glTexCoord4f(){}
void glTexCoord4i(){}
void glTexCoord4s(){}
void glTexCoord1dv(){}
void glTexCoord1fv(){}
void glTexCoord1iv(){}
void glTexCoord1sv(){}
void glTexCoord2dv(){}
void glTexCoord2fv(){}
void glTexCoord2iv(){}
void glTexCoord2sv(){}
void glTexCoord3dv(){}
void glTexCoord3fv(){}
void glTexCoord3iv(){}
void glTexCoord3sv(){}
void glTexCoord4dv(){}
void glTexCoord4fv(){}
void glTexCoord4iv(){}
void glTexCoord4sv(){}
void glRasterPos2d(){}
void glRasterPos2f(){}
void glRasterPos2i(){}
void glRasterPos2s(){}
void glRasterPos3d(){}
void glRasterPos3f(){}
void glRasterPos3i(){}
void glRasterPos3s(){}
void glRasterPos4d(){}
void glRasterPos4f(){}
void glRasterPos4i(){}
void glRasterPos4s(){}
void glRasterPos2dv(){}
void glRasterPos2fv(){}
void glRasterPos2iv(){}
void glRasterPos2sv(){}
void glRasterPos3dv(){}
void glRasterPos3fv(){}
void glRasterPos3iv(){}
void glRasterPos3sv(){}
void glRasterPos4dv(){}
void glRasterPos4fv(){}
void glRasterPos4iv(){}
void glRasterPos4sv(){}
void glRectd(){}
void glRectf(){}
void glRecti(){}
void glRects(){}
void glRectdv(){}
void glRectfv(){}
void glRectiv(){}
void glRectsv(){}
void glVertexPointer(){}
void glNormalPointer(){}
void glColorPointer(){}
void glIndexPointer(){}
void glTexCoordPointer(){}
void glEdgeFlagPointer(){}
void glGetPointerv(){}
void glArrayElement(){}
void glDrawArrays(){}
void glDrawElements(){}
void glInterleavedArrays(){}
void glShadeModel(){}
void glLightf(){}
void glLighti(){}
void glLightfv(){}
void glLightiv(){}
void glGetLightfv(){}
void glGetLightiv(){}
void glLightModelf(){}
void glLightModeli(){}
void glLightModelfv(){}
void glLightModeliv(){}
void glMaterialf(){}
void glMateriali(){}
void glMaterialfv(){}
void glMaterialiv(){}
void glGetMaterialfv(){}
void glGetMaterialiv(){}
void glColorMaterial(){}
void glPixelZoom(){}
void glPixelStoref(){}
void glPixelStorei(){}
void glPixelTransferf(){}
void glPixelTransferi(){}
void glPixelMapfv(){}
void glPixelMapuiv(){}
void glPixelMapusv(){}
void glGetPixelMapfv(){}
void glGetPixelMapuiv(){}
void glGetPixelMapusv(){}
void glBitmap(){}
void glReadPixels(){}
void glDrawPixels(){}
void glCopyPixels(){}
void glStencilFunc(){}
void glStencilMask(){}
void glStencilOp(){}
void glClearStencil(){}
void glTexGend(){}
void glTexGenf(){}
void glTexGeni(){}
void glTexGendv(){}
void glTexGenfv(){}
void glTexGeniv(){}
void glGetTexGendv(){}
void glGetTexGenfv(){}
void glGetTexGeniv(){}
void glTexEnvf(){}
void glTexEnvi(){}
void glTexEnvfv(){}
void glTexEnviv(){}
void glGetTexEnvfv(){}
void glGetTexEnviv(){}
void glTexParameterf(){}
void glTexParameteri(){}
void glTexParameterfv(){}
void glTexParameteriv(){}
void glGetTexParameterfv(){}
void glGetTexParameteriv(){}
void glTexLevelParameterfv(){}
void glTexLevelParameteriv(){}
void glGetTexLevelParameterfv(){}
void glGetTexLevelParameteriv(){}
void glTexImage1D(){}
void glTexImage2D(){}
void glTexImage3D(){}
void glGetTexImage(){}
void glGenTextures(){}
void glDeleteTextures(){}
void glBindTexture(){}
void glPrioritizeTextures(){}
void glAreTexturesResident(){}
void glIsTexture(){}
void glTexSubImage1D(){}
void glTexSubImage2D(){}
void glTexSubImage3D(){}
void glCopyTexImage1D(){}
void glCopyTexImage2D(){}
void glCopyTexSubImage1D(){}
void glCopyTexSubImage2D(){}
void glCopyTexSubImage3D(){}
void glMap1d(){}
void glMap1f(){}
void glMap2d(){}
void glMap2f(){}
void glGetMapdv(){};
void glGetMapfv(){};
void glGetMapiv(){};
void glEvalCoord1d(){}
void glEvalCoord1f(){}
void glEvalCoord1dv(){}
void glEvalCoord1fv(){}
void glEvalCoord2d(){}
void glEvalCoord2f(){}
void glEvalCoord2dv(){}
void glEvalCoord2fv(){}
void glMapGrid1d(){}
void glMapGrid1f(){}
void glMapGrid2d(){}
void glMapGrid2f(){}
void glEvalPoint1(){}
void glEvalPoint2(){}
void glEvalMesh1(){}
void glEvalMesh2(){}
void glFogf(){}
void glFogi(){}
void glFogfv(){}
void glFogiv(){}
void glFeedbackBuffer(){}
void glPassThrough(){}
void glSelectBuffer(){}
void glInitNames(){}
void glLoadName(){}
void glPushName(){}
void glPopName(){}
void glBlendEquationEXT(){}
void glBlendColorEXT(){}
void glPolygonOffsetEXT(){}
void glVertexPointerEXT(){}
void glNormalPointerEXT(){}
void glColorPointerEXT(){}
void glIndexPointerEXT(){}
void glTexCoordPointerEXT(){}
void glEdgeFlagPointerEXT(){}
void glGetPointervEXT(){}
void glArrayElementEXT(){}
void glDrawArraysEXT(){}
void glGenTexturesEXT(){}
void glDeleteTexturesEXT(){}
void glBindTextureEXT(){}
void glPrioritizeTexturesEXT(){}
void glAreTexturesResidentEXT(){}
void glIsTextureEXT(){}
void glTexImage3DEXT(){}
void glTexSubImage3DEXT(){}
void glCopyTexSubImage3DEXT(){}
void glColorTableEXT(){}
void glColorSubTableEXT(){}
void glGetColorTableEXT(){}
void glGetColorTableParameterfvEXT(){}
void glGetColorTableParameterivEXT(){}
void glMultiTexCoord1dSGIS(){}
void glMultiTexCoord1dvSGIS(){}
void glMultiTexCoord1fSGIS(){}
void glMultiTexCoord1fvSGIS(){}
void glMultiTexCoord1iSGIS(){}
void glMultiTexCoord1ivSGIS(){}
void glMultiTexCoord1sSGIS(){}
void glMultiTexCoord1svSGIS(){}
void glMultiTexCoord2dSGIS(){}
void glMultiTexCoord2dvSGIS(){}
void glMultiTexCoord2fSGIS(){}
void glMultiTexCoord2fvSGIS(){}
void glMultiTexCoord2iSGIS(){}
void glMultiTexCoord2ivSGIS(){}
void glMultiTexCoord2sSGIS(){}
void glMultiTexCoord2svSGIS(){}
void glMultiTexCoord3dSGIS(){}
void glMultiTexCoord3dvSGIS(){}
void glMultiTexCoord3fSGIS(){}
void glMultiTexCoord3fvSGIS(){}
void glMultiTexCoord3iSGIS(){}
void glMultiTexCoord3ivSGIS(){}
void glMultiTexCoord3sSGIS(){}
void glMultiTexCoord3svSGIS(){}
void glMultiTexCoord4dSGIS(){}
void glMultiTexCoord4dvSGIS(){}
void glMultiTexCoord4fSGIS(){}
void glMultiTexCoord4fvSGIS(){}
void glMultiTexCoord4iSGIS(){}
void glMultiTexCoord4ivSGIS(){}
void glMultiTexCoord4sSGIS(){}
void glMultiTexCoord4svSGIS(){}
void glMultiTexCoordPointerSGIS(){}
void glSelectTextureSGIS(){}
void glSelectTextureCoordSetSGIS(){}
void glMultiTexCoord1dEXT(){}
void glMultiTexCoord1dvEXT(){}
void glMultiTexCoord1fEXT(){}
void glMultiTexCoord1fvEXT(){}
void glMultiTexCoord1iEXT(){}
void glMultiTexCoord1ivEXT(){}
void glMultiTexCoord1sEXT(){}
void glMultiTexCoord1svEXT(){}

void glMultiTexCoord2dEXT(){}
void glMultiTexCoord2dvEXT(){}
void glMultiTexCoord2fEXT(){}
void glMultiTexCoord2fvEXT(){}
void glMultiTexCoord2iEXT(){}
void glMultiTexCoord2ivEXT(){}
void glMultiTexCoord2sEXT(){}
void glMultiTexCoord2svEXT(){}

void glMultiTexCoord3dEXT(){}
void glMultiTexCoord3dvEXT(){}
void glMultiTexCoord3fEXT(){}
void glMultiTexCoord3fvEXT(){}
void glMultiTexCoord3iEXT(){}
void glMultiTexCoord3ivEXT(){}
void glMultiTexCoord3sEXT(){}
void glMultiTexCoord3svEXT(){}

void glMultiTexCoord4dEXT(){}
void glMultiTexCoord4dvEXT(){}
void glMultiTexCoord4fEXT(){}
void glMultiTexCoord4fvEXT(){}
void glMultiTexCoord4iEXT(){}
void glMultiTexCoord4ivEXT(){}
void glMultiTexCoord4sEXT(){}
void glMultiTexCoord4svEXT(){}
void glInterleavedTextureCoordSetsEXT(){}
void glSelectTextureEXT(){}
void glSelectTextureCoordSetEXT(){}
void glSelectTextureTransformEXT(){}
void glPointParameterfEXT(){}
void glPointParameterfvEXT(){}
void glWindowPos2iMESA(){}
void glWindowPos2sMESA(){}
void glWindowPos2fMESA(){}
void glWindowPos2dMESA(){}
void glWindowPos2ivMESA(){}
void glWindowPos2svMESA(){}
void glWindowPos2fvMESA(){}
void glWindowPos2dvMESA(){}

void glWindowPos3iMESA(){}
void glWindowPos3sMESA(){}
void glWindowPos3fMESA(){}
void glWindowPos3dMESA(){}
void glWindowPos3ivMESA(){}
void glWindowPos3svMESA(){}
void glWindowPos3fvMESA(){}
void glWindowPos3dvMESA(){}

void glWindowPos4iMESA(){}
void glWindowPos4sMESA(){}
void glWindowPos4fMESA(){}
void glWindowPos4dMESA(){}
void glWindowPos4ivMESA(){}
void glWindowPos4svMESA(){}
void glWindowPos4fvMESA(){}
void glWindowPos4dvMESA(){}
void glResizeBuffersMESA(){}
void glDrawRangeElements(){}
void gluLookAt(){}
void gluOrtho2D(){}
void gluPerspective(){}
void gluPickMatrix(){}
void gluProject(){}
void gluUnProject(){}
void gluErrorString(){}
void gluScaleImage(){}
void gluBuild1DMipmaps(){}
void gluBuild2DMipmaps(){}
void gluNewQuadric(){}
void gluDeleteQuadric(){}
void gluQuadricDrawStyle(){}
void gluQuadricOrientation(){}
void gluQuadricNormals(){}
void gluQuadricTexture(){}
void gluQuadricCallback(){}
void gluCylinder(){}
void gluSphere(){}
void gluDisk(){}
void gluPartialDisk(){}
void gluNewNurbsRenderer(){}
void gluDeleteNurbsRenderer(){}
void gluLoadSamplingMatrices(){}
void gluNurbsProperty(){}
void gluGetNurbsProperty(){}
void gluBeginCurve(){}
void gluEndCurve(){}
void gluNurbsCurve(){}
void gluBeginSurface(){}
void gluEndSurface(){}
void gluNurbsSurface(){}
void gluBeginTrim(){}
void gluEndTrim(){}
void gluPwlCurve(){}
void gluNurbsCallback(){}
void gluNewTess(){}
void gluTessCallback(){}
void gluDeleteTess(){}
void gluBeginPolygon(){}
void gluEndPolygon(){}
void gluNextContour(){}
void gluTessVertex(){}
void gluGetString(){}




